# Generated by Django 5.2.15 on 2026-07-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('staff', 'date')},
        ),
    ]
